//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_item_warehouse_details
    {
        public int id { get; set; }
        public int inventory_item_id { get; set; }
        public int warehouse_id { get; set; }
        public Nullable<decimal> chop_price { get; set; }
        public Nullable<decimal> length_price { get; set; }
        public Nullable<decimal> assemble_price { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public Nullable<decimal> split_price { get; set; }
        public Nullable<int> reorder_point { get; set; }
        public bool reorder_point_locked { get; set; }
        public Nullable<int> reorder_base_quantity { get; set; }
        public Nullable<decimal> waste_factor { get; set; }
        public bool waste_factor_locked { get; set; }
        public string zone { get; set; }
        public Nullable<int> location_sort_order { get; set; }
        public bool website { get; set; }
        public string location { get; set; }
        public Nullable<int> item_location_id { get; set; }
        public Nullable<int> waste_factor_timeframe { get; set; }
        public Nullable<int> inventory_item_prompt_id { get; set; }
        public Nullable<int> catalog_id { get; set; }
        public Nullable<int> sub_catalog_id { get; set; }
        public bool glass_report { get; set; }
        public Nullable<decimal> sample_price { get; set; }
        public Nullable<decimal> rail_price { get; set; }
        public bool is_deleted { get; set; }
        public string notes { get; set; }
        public bool non_stock_item { get; set; }
        public Nullable<bool> special_order { get; set; }
        public bool taxable { get; set; }
    
        public virtual inventory_items inventory_items { get; set; }
    }
}
